"""
Tests for the spacecraft catalog and keyword matching.

These tests accept both curated instrument names (e.g., "MAG", "SWEPAM")
and auto-generated InstrumentType-based names (e.g., "mag", "plasma").
The actual names depend on whether the mission JSON was hand-curated or
auto-generated by bootstrap.py with CDAWeb metadata.

Run with: python -m pytest tests/test_catalog.py
"""

import pytest
from knowledge.catalog import (
    SPACECRAFT,
    list_spacecraft,
    list_instruments,
    get_datasets,
    match_spacecraft,
    match_instrument,
    search_by_keywords,
)


# ---------------------------------------------------------------------------
# Helpers for flexible instrument assertions
# ---------------------------------------------------------------------------

def _has_instrument_any(spacecraft_id: str, acceptable_ids: list[str]) -> bool:
    """Check if a spacecraft has at least one of the acceptable instrument IDs."""
    sc = SPACECRAFT.get(spacecraft_id)
    if not sc:
        return False
    return any(inst_id in sc["instruments"] for inst_id in acceptable_ids)


def _find_dataset_in_any_instrument(spacecraft_id: str, dataset_id: str) -> bool:
    """Check if a dataset ID exists in any instrument of the spacecraft."""
    sc = SPACECRAFT.get(spacecraft_id)
    if not sc:
        return False
    for inst in sc["instruments"].values():
        if dataset_id in inst["datasets"]:
            return True
    return False


class TestListSpacecraft:
    def test_returns_all_spacecraft(self):
        spacecraft = list_spacecraft()
        assert len(spacecraft) >= 8  # 8 curated + auto-generated missions
        ids = [s["id"] for s in spacecraft]
        assert "PSP" in ids
        assert "SolO" in ids
        assert "ACE" in ids
        assert "OMNI" in ids
        assert "WIND" in ids
        assert "DSCOVR" in ids
        assert "MMS" in ids
        assert "STEREO_A" in ids

    def test_returns_dicts_with_id_and_name(self):
        spacecraft = list_spacecraft()
        for s in spacecraft:
            assert "id" in s
            assert "name" in s


class TestListInstruments:
    def test_psp_instruments(self):
        instruments = list_instruments("PSP")
        ids = [i["id"] for i in instruments]
        # PSP must have at least 5 instruments (curated or auto-generated)
        assert len(instruments) >= 5
        # Must have magnetic field instrument (curated: FIELDS/MAG, auto: mag)
        assert any(i in ids for i in ("FIELDS/MAG", "mag"))
        # Must have a plasma instrument (curated: SWEAP, auto: plasma)
        assert any(i in ids for i in ("SWEAP", "plasma"))
        # Must have an energetic particles instrument (curated: ISOIS, auto: particles)
        assert any(i in ids for i in ("ISOIS", "particles"))

    def test_ace_instruments(self):
        instruments = list_instruments("ACE")
        ids = [i["id"] for i in instruments]
        # ACE can have curated (MAG, SWEPAM) or auto-generated (mag, plasma)
        # or just General if not yet re-bootstrapped
        # At minimum there should be at least 1 instrument
        assert len(instruments) >= 1
        # If more than just General, check for magnetic/plasma grouping
        if len(instruments) >= 2:
            assert any(i in ids for i in ("MAG", "mag"))
            assert any(i in ids for i in ("SWEPAM", "plasma"))

    def test_invalid_spacecraft_returns_empty(self):
        instruments = list_instruments("INVALID")
        assert instruments == []


class TestGetDatasets:
    def test_psp_mag_datasets(self):
        # PSP mag dataset should exist in FIELDS/MAG or mag instrument
        datasets = get_datasets("PSP", "FIELDS/MAG")
        if not datasets:
            datasets = get_datasets("PSP", "mag")
        assert "PSP_FLD_L2_MAG_RTN_1MIN" in datasets

    def test_ace_mag_datasets(self):
        # AC_H2_MFI should exist somewhere in ACE (MAG, mag, or General)
        assert _find_dataset_in_any_instrument("ACE", "AC_H2_MFI"), \
            "AC_H2_MFI not found in any ACE instrument"

    def test_invalid_returns_empty(self):
        assert get_datasets("INVALID", "MAG") == []
        assert get_datasets("PSP", "INVALID") == []


class TestMatchSpacecraft:
    @pytest.mark.parametrize("query,expected", [
        ("parker", "PSP"),
        ("PARKER", "PSP"),
        ("psp", "PSP"),
        ("PSP", "PSP"),
        ("solar probe", "PSP"),
        ("solar orbiter", "SolO"),
        ("solo", "SolO"),
        ("orbiter", "SolO"),
        ("ace", "ACE"),
        ("ACE", "ACE"),
        ("omni", "OMNI"),
        ("wind", "WIND"),
        ("WIND", "WIND"),
        ("dscovr", "DSCOVR"),
        ("mms", "MMS"),
        ("MMS", "MMS"),
        ("magnetospheric multiscale", "MMS"),
        ("stereo", "STEREO_A"),
        ("stereo-a", "STEREO_A"),
        ("stereo a", "STEREO_A"),
        ("unknown", None),
        ("xyz123", None),
    ])
    def test_match_spacecraft(self, query, expected):
        assert match_spacecraft(query) == expected


class TestMatchInstrument:
    """Test instrument keyword matching.

    Accepts either curated instrument IDs (FIELDS/MAG, SWEAP, ISOIS)
    or InstrumentType-based IDs (mag, plasma, particles). The actual
    result depends on whether instruments have keywords populated.
    """

    @pytest.mark.parametrize("spacecraft,query,expected_any_of", [
        # PSP magnetic field
        ("PSP", "magnetic field", ["FIELDS/MAG", "mag"]),
        ("PSP", "mag", ["FIELDS/MAG", "mag"]),
        # PSP plasma
        ("PSP", "plasma", ["SWEAP", "plasma"]),
        ("PSP", "density", ["SWEAP", "plasma"]),
        ("PSP", "velocity", ["SWEAP", "plasma"]),
        # PSP SPAN sub-instruments (only match if curated keywords exist)
        ("PSP", "isois", ["ISOIS", "particles"]),
        # SolO
        ("SolO", "magnetic", ["MAG", "mag"]),
        ("SolO", "proton", ["SWA-PAS", "plasma"]),
        # ACE
        ("ACE", "magnetic", ["MAG", "mag"]),
        ("ACE", "imf", ["MAG", "mag"]),
        ("ACE", "solar wind", ["SWEPAM", "plasma"]),
    ])
    def test_match_instrument(self, spacecraft, query, expected_any_of):
        result = match_instrument(spacecraft, query)
        if result is not None:
            assert result in expected_any_of, \
                f"match_instrument({spacecraft!r}, {query!r}) returned {result!r}, " \
                f"expected one of {expected_any_of}"
        else:
            # If no match, this is acceptable if instruments lack keywords
            # (pre-bootstrap state). Skip gracefully.
            instruments = list_instruments(spacecraft)
            inst_ids = [i["id"] for i in instruments]
            has_keywords = False
            sc = SPACECRAFT.get(spacecraft, {})
            for inst_id in expected_any_of:
                inst = sc.get("instruments", {}).get(inst_id)
                if inst and inst.get("keywords"):
                    has_keywords = True
                    break
            if has_keywords:
                pytest.fail(
                    f"match_instrument({spacecraft!r}, {query!r}) returned None "
                    f"but instruments with keywords exist: {inst_ids}"
                )

    # These sub-instrument tests only work with curated PSP data
    @pytest.mark.parametrize("query,expected_any_of", [
        ("span", ["SWEAP/SPAN-I", "plasma", "particles"]),
        ("span-i", ["SWEAP/SPAN-I", "plasma", "particles"]),
        ("ion spectrometer", ["SWEAP/SPAN-I", "plasma", "particles"]),
        ("span-e", ["SWEAP/SPAN-E", "plasma", "particles"]),
        ("electron", ["SWEAP/SPAN-E", "plasma"]),
        ("energetic particle", ["ISOIS", "particles"]),
        ("epi-hi", ["ISOIS", "particles"]),
    ])
    def test_psp_sub_instruments(self, query, expected_any_of):
        result = match_instrument("PSP", query)
        if result is not None:
            assert result in expected_any_of, \
                f"match_instrument('PSP', {query!r}) returned {result!r}, " \
                f"expected one of {expected_any_of}"
        # None is acceptable if keywords aren't populated

    def test_invalid_spacecraft_returns_none(self):
        assert match_instrument("INVALID", "magnetic") is None

    def test_no_match_returns_none(self):
        assert match_instrument("PSP", "unknown") is None


class TestSearchByKeywords:
    def test_parker_magnetic(self):
        result = search_by_keywords("parker magnetic field")
        assert result is not None
        assert result["spacecraft"] == "PSP"
        if result["instrument"] is not None:
            # Should be FIELDS/MAG or mag
            assert result["instrument"] in ("FIELDS/MAG", "mag")
            assert "PSP_FLD_L2_MAG_RTN_1MIN" in result["datasets"]

    def test_ace_solar_wind(self):
        result = search_by_keywords("ace solar wind")
        assert result is not None
        assert result["spacecraft"] == "ACE"
        if result["instrument"] is not None:
            # Should be SWEPAM or plasma
            assert result["instrument"] in ("SWEPAM", "plasma")
            # Check dataset in the matched instrument's datasets
            if result["instrument"] == "SWEPAM":
                assert "AC_H0_SWE" in result["datasets"]
            # For auto-generated 'plasma', AC_H0_SWE should be there too
            elif result["instrument"] == "plasma":
                assert "AC_H0_SWE" in result["datasets"]

    def test_spacecraft_only_no_instrument(self):
        result = search_by_keywords("parker")
        assert result is not None
        assert result["spacecraft"] == "PSP"
        # No instrument keyword, so no instrument match
        assert result["instrument"] is None
        assert result["datasets"] == []
        assert "available_instruments" in result

    def test_no_match(self):
        result = search_by_keywords("nonexistent mission xyz123")
        assert result is None

    def test_omni_combined(self):
        result = search_by_keywords("omni solar wind")
        assert result is not None
        assert result["spacecraft"] == "OMNI"
        if result["instrument"] is not None:
            # OMNI uses "Combined" (curated) or "plasma" (auto)
            assert result["instrument"] in ("Combined", "plasma")
            assert "OMNI_HRO_1MIN" in result["datasets"]

    def test_wind_magnetic(self):
        result = search_by_keywords("wind magnetic")
        assert result is not None
        assert result["spacecraft"] == "WIND"
        if result["instrument"] is not None:
            assert "WI_H2_MFI" in result["datasets"]

    def test_dscovr_plasma(self):
        result = search_by_keywords("dscovr plasma")
        assert result is not None
        assert result["spacecraft"] == "DSCOVR"
        if result["instrument"] is not None:
            assert result["instrument"] in ("FC", "plasma")

    def test_mms_magnetic(self):
        result = search_by_keywords("mms magnetic")
        assert result is not None
        assert result["spacecraft"] == "MMS"
        if result["instrument"] is not None:
            assert result["instrument"] in ("FGM", "mag")
            assert "MMS1_FGM_SRVY_L2@0" in result["datasets"]

    def test_stereo_magnetic(self):
        result = search_by_keywords("stereo magnetic")
        assert result is not None
        assert result["spacecraft"] == "STEREO_A"
        if result["instrument"] is not None:
            assert result["instrument"] in ("MAG", "mag")
            assert "STA_L1_MAG_RTN" in result["datasets"]
